//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoStaj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departments
    {
        public Departments()
        {
            this.Department_Arragenments = new HashSet<Department_Arragenments>();
            this.Employees = new HashSet<Employees>();
        }
    
        public int Department_ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Department_Arragenments> Department_Arragenments { get; set; }
        public virtual ICollection<Employees> Employees { get; set; }
    }
}
