//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoStaj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department_Arragenments
    {
        public int Arrangement_ID { get; set; }
        public Nullable<int> Department_ID { get; set; }
        public Nullable<int> Manager_ID { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual Managers Managers { get; set; }
    }
}
